ARG BASE_IMAGE
FROM ${BASE_IMAGE}

## TODO: change to the scripts for just compiling
## TODO: from gazebo rosdep install --skip-keys=SKIP_KEYS --skip-keys='' ... gazebo9 libgazebo9-dev ...

RUN mkdir -p /ros_home/log && chmod a+rwx /ros_home && chmod a+rwx /ros_home/log

RUN echo -e '#!/bin/bash\n\
set -e\n\
source /my_entryrc\n\
exec "$@"\n' >> /my_entrypoint.sh

RUN chmod a+x /my_entrypoint.sh

RUN echo -e '# setup ros environment\n\
if [ -e "${DOCKER_ROS_SETUP}" ]; then\n\
    source "${DOCKER_ROS_SETUP}"\n\
else\n\
    source "/opt/ros/$ROS_DISTRO/setup.bash"\n\
fi\n\
MY_IP=${DOCKER_ROS_IP:-$(hostname -i)}\n\
if [ "$ROS_IP" == "" ]; then\n\
    export ROS_IP=${MY_IP}\n\
fi\n\
if [ "$ROS_HOSTNAME" == "" ]; then\n\
    export ROS_HOSTNAME=${MY_IP}\n\
fi\n\
if [ "${DOCKER_ROS_MASTER_URI}" != "" ]; then\n\
    export ROS_MASTER_URI=${DOCKER_ROS_MASTER_URI}\n\
fi\n\
export HOME=/ros_home\n\
export ROS_HOME=/ros_home\n' >>  /my_entryrc

ENTRYPOINT ["/my_entrypoint.sh"]
CMD ["roslaunch", "robot_assembler", "kxr_assembler.launch"]
